version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm run install:dynamodb
      - npm run install:client

  pre_build:
    commands:
      - npm run test

  build:
    commands:
      - npm run deploy dev

